#ifndef CONFIG_H
#define CONFIG_H

#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_DATA_REGISTERS 16
#define CHIP8_STACK_DEPTH 16
#define CHIP8_NUMBER_OF_KEYS 16
#define CHIP8_WIDTH 64
#define CHIP8_HEIGHT 32
#define CHIP8_CHARACTER_SET_LOAD_ADDRESS 0x00
#define CHIP8_CHARACTER_SET_DEFAULT_HEIGHT 5
#define CHIP8_LOAD_ADDRESS 0x200

#define EMULATOR_WINDOW_TITLE "CHIP8 Emulator"
#define EMULATOR_RESOLUTION_MULTIPLIER 10
#define EMULATOR_WINDOW_WIDTH CHIP8_WIDTH * EMULATOR_RESOLUTION_MULTIPLIER
#define EMULATOR_WINDOW_HEIGHT CHIP8_HEIGHT * EMULATOR_RESOLUTION_MULTIPLIER

#endif